[project]
version="0.1.0"
# relative path is the path relative
# to this template file
src="package/src/module.jl"

[project.test]
file="package/test/runtests.jl"
project=false

[readme]
file = "package/README.md"
destination = "README.md"
inline_badges = false

[license]
name = "MIT"
# path= "<path to license file>"
destination = "LICENSE"

[git]
ignore = []
# name = "<your name>"
# email = "<your email>"
# branch = "<default branch name>"
ssh = false
jl = true
manifest = false
gpgsign = false
