name = "comonicon-sysimg"

[CompatHelper]

[Git]

[License]

[ProjectFile]

[Readme]

[SrcDir]

[TagBot]

[Tests]

[GitHubActions]

[Codecov]

[Documenter]
depoly = "GitHubActions"
canonical_url = true

[Comonicon]

[SystemImage]
